### PR TITLE
Prepare release 0.24.0

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Review by billy-doyle — APPROVED** [review]
lgtm lfg 🔥

**Comment by JelleZijlstra** [comment]
Upload failed, I think it's because the project name doesn't match. Figuring out how to fix that in poetry.

**Comment by JelleZijlstra** [comment]
Worked the second time around: https://pypi.org/project/compat-fork-diagrams/0.24.1/

**Comment by billy-doyle** [comment]
excellent!

**Pull request merged**
